### ISSUE TITLE
Flask-HAL

### ISSUE THREAD

**Issue by krak3n** [mikekelly/hal_specification#27]
Hey

We just released a Python Flask extension which implements the `HAL` specification. Would be cool if you could add to the wiki of libraries.

https://pypi.python.org/pypi/Flask-HAL

Thanks,

Chris

**Comment by mikekelly** [comment]
Hi Chris, you should be able to edit the wiki yourself. I'd prefer to let
the community manage it themselves since it avoids me becoming the
bottleneck!

On Mon, Aug 10, 2015 at 12:54 PM, Chris Reeves <notifications@github.com>
wrote:

> Hey
>
> We just released a Python Flask extension which implements the HAL
> specification. Would be cool if you could add to the wiki of libraries.
>
> https://pypi.python.org/pypi/Flask-HAL
>
> Thanks,
>
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikekelly/hal_specification/issues/27>.
>



-- 
Mike

http://twitter.com/mikekelly85
http://github.com/mikekelly
http://linkedin.com/in/mikekelly123

**Comment by krak3n** [comment]
Ok cool thanks @mikekelly :+1:
